# For more info: man 5 alacritty

[general]
import = [
    "vampirella-theme.toml"
]

[font]
normal = { family = "Hurmit Nerd Font", style = "Regular" }
size = 11
offset = { x = 0, y = -4 }

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
